In [1]:
import numpy as np

a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [2]:
import time

x=np.random.rand(1000000)
y=np.random.rand(1000000)

tic=time.time()
z=np.dot(x,y)
toc=time.time()

print(z)

print('Vectorized version:'+str(1000*(toc-tic))+'ms')

c=0
tic=time.time()
for i in range(1000000):
    c+=x[i]*y[i]
toc=time.time()

print(c)
print('For loop:'+str(1000*(toc-tic))+'ms')

250071.82679531095
Vectorized version:1435.603380203247ms
250071.82679531878
For loop:793.4954166412354ms


In [5]:
a = np.random.randn(3, 3)
print(a,'\n')
b = np.random.randn(3, 1)
print(b,'\n')
c = a*b
print(c)

[[ 0.68984209  0.05253208 -1.50278015]
 [-1.71863809 -0.42387342  0.760026  ]
 [-1.07262856 -0.75892562 -0.61876197]] 

[[-0.50568542]
 [ 1.5388315 ]
 [ 1.39441425]] 

[[-0.34884309 -0.0265647   0.75993401]
 [-2.64469442 -0.65226978  1.16955194]
 [-1.49568855 -1.0582567  -0.86281052]]
